/* delonix — generated full feature mockup catalog from FEATURES.md */
const FEATURE_MATRIX = [
  {
    "title": "Core Billing Engine",
    "features": [
      "Subscription management (create, modify, pause, resume, cancel)",
      "One-time / ad hoc charges",
      "Recurring billing (daily, weekly, monthly, quarterly, annual, custom cycles)",
      "Prorated billing on mid-cycle changes",
      "Metered / usage-based billing",
      "Tiered pricing (graduated & volume)",
      "Volume pricing",
      "Flat-rate pricing",
      "Per-seat / per-user pricing",
      "Hybrid pricing models (base + usage)",
      "Freemium plan support",
      "Free trial management",
      "Trial-to-paid conversion automation",
      "Prepaid billing",
      "Postpaid billing",
      "Billing period alignment (first-of-month normalization)",
      "Mid-cycle plan changes with immediate or deferred effect",
      "Backdating charges",
      "Billing anchors / custom billing dates",
      "Minimum spend commitments",
      "Overage handling"
    ]
  },
  {
    "title": "Pricing & Plans",
    "features": [
      "Plan catalog with versioning",
      "Price books (multiple, per segment or region)",
      "Geographic / regional pricing",
      "Custom pricing per customer",
      "Pricing rules engine",
      "Volume discounts",
      "Multi-year pricing tiers",
      "Contractual price locks",
      "Promotional / limited-time pricing",
      "Discount management (percentage, fixed, duration-limited)",
      "Coupons and redemption codes",
      "Product bundling",
      "Add-ons and extras",
      "Entitlements per plan",
      "Feature flags tied to plan level",
      "Price localization (currency + format)",
      "Standalone selling price (SSP) configuration"
    ]
  },
  {
    "title": "Invoice Management",
    "features": [
      "Automated invoice generation",
      "Invoice templates (customizable branding)",
      "Custom invoice numbering / sequencing",
      "Invoice scheduling and batching",
      "Consolidated invoices (multiple subscriptions \u2192 one invoice)",
      "Invoice grouping by cost center or department",
      "Credit notes / credit memos",
      "Debit notes",
      "Proforma invoices",
      "Manual invoice creation",
      "Invoice editing before finalization",
      "Invoice voiding and reissue",
      "Invoice approval workflows",
      "Multi-language invoices",
      "Invoice delivery (email, PDF, EDI 810, XML)",
      "Invoice archiving with retention policies",
      "Invoice history and audit trail",
      "E-invoicing compliance (Peppol, ZUGFeRD, Factur-X, FatturaPA, etc.)",
      "Invoice watermarking",
      "Purchase order (PO) number capture and matching"
    ]
  },
  {
    "title": "Payment Processing",
    "features": [
      "Credit/debit card (Visa, Mastercard, Amex, Discover)",
      "ACH / eCheck (US bank transfer)",
      "Wire transfers",
      "SEPA direct debit (EU)",
      "BACS direct debit (UK)",
      "Faster Payments (UK)",
      "SPEI (Mexico)",
      "PayPal, Venmo, Cash App Pay",
      "Digital wallets (Apple Pay, Google Pay, Samsung Pay)",
      "Buy Now Pay Later (Klarna, Afterpay, Affirm)",
      "Cryptocurrency payments",
      "Check / cheque payments",
      "Net terms (Net 15, Net 30, Net 60, Net 90)",
      "Payment links (one-click hosted checkout)",
      "Hosted payment pages (white-labeled)",
      "Payment on file (stored tokenized methods)",
      "Multiple payment methods per customer",
      "Payment splitting across methods",
      "Auto-charge (card on file)",
      "Payment retry on failure",
      "Smart retry scheduling (ML-optimized timing)",
      "3D Secure (3DS2) / SCA compliance",
      "Strong Customer Authentication (EU PSD2)",
      "PCI DSS Level 1 compliance",
      "Tokenization and vault management",
      "Partial payments",
      "Overpayment handling",
      "Real-time payment confirmation"
    ]
  },
  {
    "title": "Dunning Management",
    "features": [
      "Automated payment failure sequences",
      "Configurable dunning cadence (timing, channels)",
      "Soft vs. hard decline handling",
      "Card updater (automatic card number refresh via Visa/Mastercard)",
      "Smart retry using ML card success prediction",
      "Grace period configuration",
      "Account suspension / access revocation on non-payment",
      "Escalation rules (email \u2192 call \u2192 collections)",
      "Reactivation workflows post-payment",
      "Dunning email templates per failure stage",
      "Dunning analytics (recovery rate, revenue recovered)",
      "Pause dunning for specific customers"
    ]
  },
  {
    "title": "Revenue Recognition",
    "features": [
      "ASC 606 compliance",
      "IFRS 15 compliance",
      "Deferred revenue tracking and scheduling",
      "Revenue schedules (ratable, event-based, milestone)",
      "Performance obligation management",
      "Multi-element arrangement (MEA) handling",
      "Contract modification and re-evaluation",
      "Standalone selling price (SSP) calculation",
      "Revenue waterfall reports",
      "Recognized vs. deferred revenue split",
      "Revenue accrual entries",
      "Variable consideration handling (refunds, discounts, rebates)",
      "Forecasted revenue recognition",
      "Period-close controls"
    ]
  },
  {
    "title": "Tax Management",
    "features": [
      "Multi-jurisdiction tax calculation engine",
      "US sales tax (all 50 states + local jurisdictions)",
      "VAT (EU 27 member states, UK, Norway, Switzerland)",
      "GST/HST (Canada)",
      "GST (Australia, New Zealand, India, Singapore)",
      "JCT (Japan Consumption Tax)",
      "Digital Services Tax (DST)",
      "Withholding tax",
      "Reverse charge mechanism",
      "Economic nexus tracking and alerts",
      "Tax exemptions (reseller, non-profit, government)",
      "Tax exemption certificate management",
      "Tax ID validation (VAT ID, EIN, ABN, GST, etc.)",
      "Automatic tax rate updates",
      "Tax override capability",
      "Tax-inclusive vs. tax-exclusive pricing",
      "Integration with Avalara, TaxJar, Vertex, Taxamo",
      "Tax reports by jurisdiction",
      "VAT return data export",
      "MTD (Making Tax Digital) compliance (UK)",
      "OSS / IOSS compliance (EU)"
    ]
  },
  {
    "title": "Customer & Account Management",
    "features": [
      "Customer profiles (individual and company)",
      "Account hierarchy (parent \u2192 child / subsidiary accounts)",
      "Multiple contacts per account with roles",
      "Multiple billing addresses",
      "Shipping address management",
      "Custom fields on customer records",
      "Customer segmentation and tagging",
      "Customer notes and internal annotations",
      "Communication history log",
      "Account merge / deduplication",
      "Bulk customer import / export",
      "Customer credit limit management",
      "Customer credit score / risk tier",
      "Account health score",
      "Customer lifecycle stage tracking"
    ]
  },
  {
    "title": "Subscription Lifecycle Management",
    "features": [
      "Upgrade and downgrade flows",
      "Immediate vs. end-of-period plan changes",
      "Subscription cloning / templating",
      "Bulk subscription operations",
      "Subscription pausing (with optional billing pause)",
      "Cancellation workflows with reason capture",
      "Cancellation surveys",
      "Win-back / re-engagement flows",
      "Subscription reactivation",
      "Subscription renewal management",
      "Auto-renewal with configurable advance notice",
      "Renewal quote generation",
      "Co-term / alignment of multiple subscriptions",
      "Subscription transfer between accounts"
    ]
  },
  {
    "title": "Contract Management",
    "features": [
      "Contract creation and versioning",
      "Multi-year contracts",
      "Contract terms and conditions capture",
      "Custom contract start / end dates",
      "Evergreen vs. fixed-term contracts",
      "Auto-renewal with notification windows",
      "Contract amendments and addenda",
      "Minimum commitment / floor ARR",
      "Contract performance obligation tracking",
      "Electronic signature integration (DocuSign, Adobe Sign, HelloSign)",
      "Quote-to-contract flow",
      "Contract repository and search",
      "Renewal pipeline management",
      "Early termination fee calculation"
    ]
  },
  {
    "title": "CPQ (Configure, Price, Quote)",
    "features": [
      "Product catalog for quoting",
      "Guided selling / product configuration wizard",
      "Rules-based pricing configuration",
      "Quote generation with line items",
      "Tiered discount approval workflows",
      "Quote templates",
      "Quote expiry and versioning",
      "Quote PDF generation and delivery",
      "Quote-to-order / quote-to-subscription conversion",
      "Proposal generation",
      "Competitive pricing comparison",
      "Deal desk workflows",
      "Opportunity-to-billing sync (CRM integration)"
    ]
  },
  {
    "title": "Accounts Receivable",
    "features": [
      "Payment application to invoices",
      "Auto-application of payments",
      "Unapplied payment management",
      "Write-offs and bad debt",
      "Dispute management and resolution tracking",
      "Collections workflow management",
      "AR aging reports (30/60/90/120+)",
      "Cash flow forecasting from AR",
      "Customer credit holds",
      "Balance forward invoices",
      "Statement of account generation",
      "Integration with collections agencies",
      "Promise-to-pay tracking"
    ]
  },
  {
    "title": "Refunds & Credits",
    "features": [
      "Full refunds to original payment method",
      "Partial refunds",
      "Refund to credit balance",
      "Account credit balance management",
      "Credit expiry rules",
      "Promotional credit issuance",
      "Credit application to future invoices",
      "Prepaid credit / wallet management",
      "Balance rollover configuration",
      "Refund reason tracking",
      "Refund approval workflows"
    ]
  },
  {
    "title": "Self-Service Customer Portal",
    "features": [
      "View and search invoices",
      "Download invoices as PDF",
      "Pay invoices online",
      "Set up autopay",
      "Manage saved payment methods",
      "Update billing address and contact info",
      "View subscription details",
      "Self-service plan upgrade / downgrade",
      "Self-service cancellation",
      "View usage metrics and history",
      "Download usage reports",
      "Manage users / seats (add/remove)",
      "View transaction and payment history",
      "Raise billing disputes",
      "Request refunds",
      "Download tax documents",
      "Accept/decline quotes and contracts",
      "View and accept renewal quotes",
      "Branded and embeddable portal (configuration UI)"
    ]
  },
  {
    "title": "Reporting & Analytics",
    "features": [
      "MRR (Monthly Recurring Revenue)",
      "ARR (Annual Recurring Revenue)",
      "Net Revenue Retention (NRR)",
      "Gross Revenue Retention (GRR)",
      "Net Dollar Retention (NDR)",
      "Customer Lifetime Value (LTV)",
      "Average Revenue Per User (ARPU)",
      "Churn rate (customer churn & revenue churn)",
      "Logo churn vs. revenue churn",
      "Expansion revenue",
      "Contraction revenue",
      "New business revenue",
      "Reactivation revenue",
      "Revenue by product / plan / segment / geo",
      "Cohort analysis (monthly cohorts)",
      "Trial conversion rates",
      "Subscriber counts (new, active, churned, net)",
      "Cash flow reports",
      "Deferred revenue balance",
      "Revenue waterfall (beginning \u2192 end of period)",
      "Bookings vs. billings vs. revenue",
      "Accounts receivable aging",
      "Collections effectiveness",
      "Payment success rates by method",
      "Dashboard builder (drag-and-drop)",
      "Custom report builder",
      "Scheduled report delivery (email, Slack)",
      "Report export (CSV, PDF, Excel, Google Sheets)",
      "Real-time dashboards",
      "Benchmark comparisons (industry averages)",
      "Forecasting and projections"
    ]
  },
  {
    "title": "Usage & Metering",
    "features": [
      "Real-time usage event ingestion (REST API)",
      "High-throughput event pipeline (millions of events/day)",
      "Usage aggregation (sum, max, unique count, percentile)",
      "Multiple concurrent usage meters per subscription",
      "Usage-based overages (hard cap vs. overage billing)",
      "Usage alerts and threshold notifications",
      "Usage caps / hard limits",
      "Rollover unused units to next period",
      "Usage history per customer",
      "Usage rating engine",
      "Idempotent event deduplication",
      "Usage report per invoice",
      "Usage debugging and audit log",
      "Proration of usage within a billing period"
    ]
  },
  {
    "title": "Multi-entity & Multi-tenancy",
    "features": [
      "Multiple legal entity support",
      "Inter-company billing",
      "Subsidiary management",
      "Multi-brand billing (different logos/names per entity)",
      "Multi-currency at entity level",
      "Consolidated cross-entity reporting",
      "Entity-level chart of accounts",
      "Separate GL per entity",
      "Shared customer database across entities"
    ]
  },
  {
    "title": "Financial Controls & General Ledger",
    "features": [
      "GL account mapping per product / revenue type",
      "Chart of accounts management",
      "Journal entry generation (automated + manual)",
      "Revenue accrual entries",
      "Period-close controls (lock closed periods)",
      "Audit trail on all financial transactions",
      "Approval limits by amount or type",
      "Segregation of duties enforcement",
      "Intercompany eliminations",
      "Foreign currency revaluation",
      "Realized / unrealized FX gain/loss tracking"
    ]
  },
  {
    "title": "Multi-currency & Localization",
    "features": [
      "150+ currencies",
      "Real-time exchange rates (daily feed)",
      "Fixed / locked exchange rates per contract",
      "Customer-facing currency vs. reporting currency",
      "Currency rounding rules (per jurisdiction)",
      "Functional currency for reporting",
      "Currency conversion at billing time",
      "Localized invoice date/number formats",
      "Localized tax labels",
      "Multi-language email templates and invoices",
      "Right-to-left (RTL) language support"
    ]
  },
  {
    "title": "Integrations",
    "features": [
      "Salesforce CRM",
      "HubSpot CRM",
      "Microsoft Dynamics 365 CRM",
      "Zoho CRM",
      "Pipedrive CRM",
      "SAP ERP",
      "Oracle ERP Cloud",
      "NetSuite ERP",
      "Microsoft Dynamics Finance",
      "Xero accounting",
      "QuickBooks Online",
      "Freshbooks",
      "Stripe payment gateway",
      "Adyen payment gateway",
      "Braintree payment gateway",
      "PayPal payment gateway",
      "Square",
      "Authorize.Net",
      "Checkout.com",
      "Worldpay",
      "Cybersource",
      "Avalara tax engine",
      "TaxJar tax engine",
      "Vertex tax engine",
      "DocuSign e-signature",
      "Adobe Sign e-signature",
      "HelloSign",
      "Zendesk help desk",
      "Freshdesk help desk",
      "Intercom",
      "ServiceNow",
      "Looker BI",
      "Tableau BI",
      "Power BI",
      "Snowflake data warehouse",
      "BigQuery data warehouse",
      "Amazon Redshift",
      "Okta SSO",
      "Auth0",
      "Azure Active Directory",
      "Google Workspace SSO",
      "Twilio SMS",
      "SendGrid email",
      "Mailchimp",
      "Zapier",
      "Make (Integromat)",
      "Workato",
      "Boomi",
      "Mulesoft",
      "Webhooks (configurable per event type with retry and signature verification)",
      "REST API (versioned, with full OpenAPI spec)",
      "GraphQL API",
      "Bulk data export (S3, GCS, SFTP)"
    ]
  },
  {
    "title": "Developer Platform",
    "features": [
      "Versioned REST API",
      "GraphQL API",
      "Webhooks with retry, dead-letter queue, and HMAC signatures",
      "Event catalog (full list of subscribable events)",
      "API sandbox / test mode with test clock",
      "API keys with scoped permissions",
      "OAuth 2.0 support",
      "Official SDKs (Node.js, Python, Ruby, Java, PHP, Go, .NET)",
      "SDK documentation view",
      "Postman / Insomnia collections",
      "API reference docs",
      "Changelog and deprecation policy",
      "API usage monitoring and rate limit dashboards",
      "IP allowlisting for API access",
      "Idempotency keys"
    ]
  },
  {
    "title": "Notifications & Communications",
    "features": [
      "Invoice delivery via email (configurable triggers)",
      "Payment confirmation receipts",
      "Upcoming renewal notifications",
      "Failed payment notifications",
      "Payment retry notifications",
      "Expiring payment method alerts",
      "Trial expiration warnings",
      "Account suspension notices",
      "Custom email templates (HTML + plain text)",
      "Brand theming per template",
      "Multi-language notification templates",
      "SMS notifications",
      "In-app notification feed",
      "Slack / Teams webhook notifications",
      "Communication delivery log and audit",
      "Notification preference management (per customer)",
      "Unsubscribe handling"
    ]
  },
  {
    "title": "Workflow & Automation",
    "features": [
      "Event-driven trigger engine",
      "No-code workflow builder (if/then rules)",
      "Billing lifecycle hooks (pre/post billing)",
      "Approval workflows (quotes, discounts, write-offs)",
      "Escalation rules",
      "Scheduled tasks (e.g., aging review, renewal campaigns)",
      "Automated onboarding billing sequences",
      "Win-back campaign automation",
      "Payment reminder sequence builder",
      "Integration action triggers (sync to CRM on event)"
    ]
  },
  {
    "title": "Marketplace & Partner / Channel Billing",
    "features": [
      "Reseller / channel partner management",
      "Tiered partner pricing",
      "Partner commission tracking",
      "Revenue share calculation and payout",
      "White-label billing (partner-branded)",
      "Sub-tenant provisioning",
      "Marketplace usage billing pass-through",
      "Partner self-service portal",
      "Co-sell billing flows"
    ]
  },
  {
    "title": "Security & Compliance",
    "features": [
      "PCI DSS Level 1 certification",
      "SOC 2 Type II report",
      "ISO 27001 certification",
      "GDPR compliance (data processing agreements, consent, erasure)",
      "CCPA compliance",
      "HIPAA-eligible configuration (BAA available)",
      "Role-based access control (RBAC) with custom roles",
      "Attribute-based access control (ABAC)",
      "Multi-factor authentication (MFA / TOTP / hardware keys)",
      "SSO via SAML 2.0 and OIDC",
      "SCIM provisioning (auto user sync from IdP)",
      "Field-level encryption for sensitive data",
      "Data encryption at rest (AES-256) and in transit (TLS 1.2+)",
      "Customer-managed encryption keys (CMEK / BYOK)",
      "Data residency options (US, EU, APAC)",
      "Right to erasure / anonymization",
      "Data portability export",
      "Audit logs (immutable, exportable)",
      "Session management (timeout, concurrent sessions)",
      "IP allowlisting / blocklisting",
      "Anomaly detection on user activity",
      "Penetration testing (annual third-party)",
      "Bug bounty program",
      "Vulnerability disclosure policy"
    ]
  },
  {
    "title": "Data Management & Operations",
    "features": [
      "Bulk import (CSV, JSON, API)",
      "Bulk export",
      "Data migration tooling and services",
      "Sandbox environments (per team)",
      "Test clock (simulate time travel for testing)",
      "Data archiving and retention policies",
      "Data anonymization for non-production",
      "Soft deletes with recovery window",
      "Schema / API versioning",
      "Idempotent API operations",
      "Disaster recovery (RPO/RTO SLAs)",
      "99.99% uptime SLA",
      "Status page"
    ]
  },
  {
    "title": "AI / ML Capabilities",
    "features": [
      "Churn prediction scoring",
      "Expansion revenue propensity scoring",
      "Smart dunning retry optimization (card success prediction)",
      "Revenue anomaly detection and alerts",
      "Pricing optimization recommendations",
      "Revenue forecasting models",
      "Natural language query interface (\"What was NRR last quarter?\")",
      "Automated invoice anomaly flagging",
      "Customer health score modeling",
      "AI-assisted collections prioritization"
    ]
  }
];
