/* delonix — dataops.js */

VIEWS.dataops = (v)=>{
  const jobs=[['IMP-2048','Customer import','CSV','12,480 rows','Completed','good'],['EXP-9172','Invoice archive export','S3','47,218 objects','Running','warn'],['ANON-381','Sandbox anonymization','EU sandbox','1.2M records','Queued','muted'],['REC-144','Soft-delete recovery','Account AC-5512','14 objects','Review','crit']];
  v.appendChild(el(`<div class="view">
    ${pageHead('Data Operations','Operational data management for imports, exports, sandboxes, test clocks, retention, anonymization, recovery and platform status.',`<button class="btn ghost" data-act="download" data-arg="csv|Data Jobs|184 jobs">${svg(I.download,14)} Export jobs</button><button class="btn primary" data-act="workspacecard" data-arg="dataops|Data import wizard|Source mapping, validation rules, dedupe strategy and dry-run preview">+ New import</button>`)}
    <div class="grid kpis" style="grid-template-columns:repeat(4,1fr)">${kpi('Bulk jobs','184','last 30 days',{accent:true})}${kpi('Sandbox envs','6','3 with test clock',{})}${kpi('Retention policies','14','2 pending approval',{})}${kpi('Uptime','99.99%','RPO 15m · RTO 1h',{})}</div>
    <div class="two-col" style="align-items:start"><div class="card panel"><div class="panel-head"><h3>Data jobs</h3><span class="sub">imports, exports and recovery</span></div><div class="table-wrap"><table><thead><tr><th>Job</th><th>Name</th><th>Source</th><th>Volume</th><th>Status</th></tr></thead><tbody>${jobs.map(j=>`<tr><td class="mono">${j[0]}</td><td class="nm">${j[1]}</td><td>${j[2]}</td><td>${j[3]}</td><td>${pill(j[5],j[4])}</td></tr>`).join('')}</tbody></table></div></div><div class="card panel"><div class="panel-head"><h3>Sandbox & test clock</h3></div>${['Advance test clock to next renewal','Replay webhook deliveries in sandbox','Mask PII before refresh','Lock schema version for migration rehearsal'].map((x,i)=>`<div class="set-row"><div><div class="t">${x}</div><div class="d">Environment ${['QA','Demo','EU Sandbox','Migration'][i]}</div></div><div class="spacer"></div><button class="btn ghost" style="padding:5px 10px" data-act="workspacecard" data-arg="dataops|${x}|Governed configuration — validated, approved and auditable">Run</button></div>`).join('')}</div></div>
    <div class="card panel" style="margin-top:16px"><div class="panel-head"><h3>Retention and status controls</h3><span class="sub">SLA, DR and audit evidence</span></div><div class="workflow-canvas">${['Archive invoices after 7 years','Anonymize non-prod PII weekly','Recover soft deletes within 30 days','Publish public status incident','DR drill evidence attached'].map((x,i)=>`<div class="flow-node"><i>${i+1}</i><b>${x}</b><span>${i<3?'policy active':'evidence required'}</span></div>`).join('')}</div></div>
  </div>`));
};
