/* delonix — localization.js */

VIEWS.localization = (v)=>{
  const rates=[['USD','Functional currency','1.0000','Locked'],['EUR','ECB feed','0.9321','Updated 06:00 UTC'],['GBP','Bank feed','0.7894','Updated 06:00 UTC'],['JPY','Bank feed','160.82','Rounding: nearest yen']];
  const locales=[['Germany','EUR','VAT reverse charge label','DD.MM.YYYY','Live'],['Japan','JPY','JCT tax label','YYYY/MM/DD','Live'],['United Arab Emirates','AED','RTL invoice template','DD/MM/YYYY','Review'],['United States','USD','Sales tax label','MM/DD/YYYY','Live']];
  v.appendChild(el(`<div class="view">
    ${pageHead('Currency & Localization','Currency, FX, rounding, language, invoice-format and localized tax-label controls for global billing.',`<button class="btn ghost" data-act="download" data-arg="csv|FX Rates|150 currencies">${svg(I.download,14)} Export rates</button><button class="btn primary" data-act="workspacecard" data-arg="localization|Locale preview|Language, number/date formats and per-locale invoice templates">Preview invoice</button>`)}
    <div class="grid kpis" style="grid-template-columns:repeat(4,1fr)">${kpi('Currencies','150','4 active in demo',{accent:true})}${kpi('FX locks','26','contract-level rates',{})}${kpi('Locales','18','11 invoice languages',{})}${kpi('Rounding rules','34','jurisdiction specific',{})}</div>
    <div class="two-col" style="align-items:start"><div class="card panel"><div class="panel-head"><h3>Exchange rates</h3><span class="sub">customer currency vs reporting currency</span></div><div class="table-wrap"><table><thead><tr><th>Currency</th><th>Source</th><th>Rate</th><th>Status</th></tr></thead><tbody>${rates.map(r=>`<tr><td class="nm">${r[0]}</td><td>${r[1]}</td><td class="mono">${r[2]}</td><td class="mut">${r[3]}</td></tr>`).join('')}</tbody></table></div></div><div class="card panel"><div class="panel-head"><h3>Contract FX lock</h3></div>${['Lock EUR rate for Helios Manufacturing through 2027','Bill Meridian Bank in GBP, report in USD','Apply jurisdiction rounding before tax','Use localized number/date format on invoice PDF'].map(x=>`<div class="set-row"><div><div class="t">${x}</div><div class="d">audited conversion policy</div></div><div class="spacer"></div><div class="toggle on" data-act="toggle"><i></i></div></div>`).join('')}</div></div>
    <div class="card panel" style="margin-top:16px"><div class="panel-head"><h3>Locale rules</h3></div><div class="table-wrap"><table><thead><tr><th>Market</th><th>Currency</th><th>Tax / language rule</th><th>Date format</th><th>Status</th></tr></thead><tbody>${locales.map(l=>`<tr><td class="nm">${l[0]}</td><td>${l[1]}</td><td>${l[2]}</td><td class="mono">${l[3]}</td><td>${pill(l[4]==='Live'?'good':'warn',l[4])}</td></tr>`).join('')}</tbody></table></div></div>
  </div>`));
};
