/* delonix — partnerbilling.js */

VIEWS.partnerbilling = (v)=>{
  const partners=[['Atlas Resellers','Gold','18 tenants','$84,200','12% rev share','Ready'],['Northstar Marketplace','Marketplace','9 tenants','$41,880','Usage pass-through','Reconciling'],['Helio Channel','Silver','6 tenants','$22,400','8% commission','Ready']];
  const payouts=[['PO-7812','Atlas Resellers','$10,104','Approved','Jul 03'],['PO-7811','Northstar Marketplace','$4,188','Usage review','Jul 05'],['PO-7808','Helio Channel','$1,792','Draft','Jul 08']];
  v.appendChild(el(`<div class="view">
    ${pageHead('Partner Billing','Channel billing workspace for reseller pricing, commissions, revenue share, marketplace pass-through and white-label invoices.',`<button class="btn ghost" data-act="download" data-arg="csv|Partner Ledger|33 partner statements">${svg(I.download,14)} Export ledger</button><button class="btn primary" data-act="toast" data-arg="Partner onboarding opened">+ Add partner</button>`)}
    <div class="grid kpis" style="grid-template-columns:repeat(4,1fr)">${kpi('Partner MRR','$148,480','33 active tenants',{accent:true})}${kpi('Commission due','$16,084','3 payout batches',{})}${kpi('Marketplace usage','$41,880','9 AWS-linked tenants',{})}${kpi('White-label brands','7','invoice themes active',{})}</div>
    <div class="two-col" style="align-items:start"><div class="card panel"><div class="panel-head"><h3>Partner accounts</h3><span class="sub">pricing, tenants and billing ownership</span></div><div class="table-wrap"><table><thead><tr><th>Partner</th><th>Tier</th><th>Tenants</th><th class="num">MRR</th><th>Commercials</th><th>Status</th></tr></thead><tbody>${partners.map(p=>`<tr><td class="nm">${p[0]}</td><td>${p[1]}</td><td>${p[2]}</td><td class="num tnum">${p[3]}</td><td>${p[4]}</td><td>${pill(p[5]==='Ready'?'good':'warn',p[5])}</td></tr>`).join('')}</tbody></table></div></div><div class="card panel"><div class="panel-head"><h3>Partner invoice controls</h3></div>${['White-label invoice sender and logo','Sub-tenant provisioning approval','Partner price book override','Co-sell opportunity billing split'].map((x,i)=>`<div class="set-row"><div><div class="t">${x}</div><div class="d">applies to ${i+3} partner programs</div></div><div class="spacer"></div><div class="toggle on" data-act="toggle"><i></i></div></div>`).join('')}</div></div>
    <div class="card panel" style="margin-top:16px"><div class="panel-head"><h3>Revenue-share payouts</h3></div><div class="table-wrap"><table><thead><tr><th>Payout</th><th>Partner</th><th class="num">Amount</th><th>Status</th><th>Scheduled</th></tr></thead><tbody>${payouts.map(p=>`<tr><td class="mono">${p[0]}</td><td>${p[1]}</td><td class="num tnum">${p[2]}</td><td>${pill(p[3]==='Approved'?'good':p[3]==='Draft'?'muted':'warn',p[3])}</td><td>${p[4]}</td></tr>`).join('')}</tbody></table></div></div>
  </div>`));
};
