/* delonix — paymentops.js */

VIEWS.paymentops = (v)=>{
  const rails=[['Cards','Stripe primary','3DS2 enabled','99.1% auth','good'],['ACH / eCheck','Plaid + Stripe Financial Connections','mandate verified','97.8% settle','good'],['SEPA / BACS','Adyen EU/UK','mandate review','95.4% settle','warn'],['Wire transfers','Virtual bank accounts','manual match','12 unapplied','warn'],['Wallets / BNPL','Apple Pay · Google Pay · Affirm','pilot','Ready','muted']];
  const exceptions=[['PAY-94197','Apex Systems','Hard decline','Smart retry blocked','Update payment method'],['PAY-94194','Fulcrum Labs','3DS challenge abandoned','Retry email sent','Customer action'],['UNAP-884','Meridian Bank','Wire overpayment','$2,420 unapplied','Apply to invoice']];
  v.appendChild(el(`<div class="view">
    ${pageHead('Payment Operations','Payment rail administration for cards, ACH, wires, wallets, mandates, SCA/3DS, token vaults, split payments and exception handling.',`<button class="btn ghost" data-act="route" data-arg="payments">Open ledger</button><button class="btn primary" data-act="workspacecard" data-arg="paymentops|Payment rail setup|Gateway routing, retry ladders, settlement accounts and fee rules">+ Configure rail</button>`)}
    <div class="grid kpis" style="grid-template-columns:repeat(4,1fr)">${kpi('Payment rails','9','5 active in demo',{accent:true})}${kpi('Tokenized methods','18,420','PCI vault managed',{})}${kpi('Mandates','4,881','ACH/SEPA/BACS',{})}${kpi('Exceptions','15','3 high priority',{})}</div>
    <div class="card panel"><div class="panel-head"><h3>Payment rails</h3><span class="sub">method-specific production controls</span></div><div class="table-wrap"><table><thead><tr><th>Rail</th><th>Processor</th><th>Control</th><th>Performance</th><th>Status</th></tr></thead><tbody>${rails.map(r=>`<tr><td class="nm">${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td><td>${pill(r[4],r[4]==='good'?'Live':r[4]==='warn'?'Review':'Pilot')}</td></tr>`).join('')}</tbody></table></div></div>
    <div class="two-col" style="align-items:start;margin-top:16px"><div class="card panel"><div class="panel-head"><h3>Exception workbench</h3></div><div class="table-wrap"><table><thead><tr><th>Ref</th><th>Customer</th><th>Exception</th><th>State</th><th>Next action</th></tr></thead><tbody>${exceptions.map(e=>`<tr><td class="mono">${e[0]}</td><td>${e[1]}</td><td>${e[2]}</td><td class="mut">${e[3]}</td><td>${e[4]}</td></tr>`).join('')}</tbody></table></div></div><div class="card panel"><div class="panel-head"><h3>Vault and compliance</h3></div>${['Network tokenization enabled for cards','SCA exemptions logged with evidence','Split payments require controller approval','Overpayments route to unapplied cash queue'].map(x=>`<div class="set-row"><div><div class="t">${x}</div><div class="d">payment policy active</div></div><div class="spacer"></div><div class="toggle on" data-act="toggle"><i></i></div></div>`).join('')}</div></div>
  </div>`));
};
