/* delonix — workflows.js */

VIEWS.workflows = (v)=>{
  const flows=[['Quote discount approval','quote.discount.requested','Deal Desk → Finance','Live','good'],['Billing run pre-check','billing_run.validation.failed','Tax Ops → Controller','Live','warn'],['Payment reminder sequence','invoice.past_due','Email/SMS cadence','Live','good'],['Win-back campaign','subscription.cancelled','CSM + offer approval','Draft','muted']];
  const runs=[['WF-8841','Payment reminder sequence','Step 2: SMS reminder','Cobalt Robotics','Waiting 24h'],['WF-8839','Billing run pre-check','Tax address exception','Apex Systems','Assigned'],['WF-8835','Quote discount approval','VP Finance approval','Meridian Bank','Approved'],['WF-8831','Win-back campaign','Offer generated','Solstice Media','Draft']];
  v.appendChild(el(`<div class="view">
    ${pageHead('Workflow Automation','No-code billing workflow builder for lifecycle hooks, approvals, escalations, scheduled tasks and integration actions.',`<button class="btn ghost" data-act="workflowaction" data-arg="test">Test selected flow</button><button class="btn primary" data-act="workflowaction" data-arg="builder">+ Build workflow</button>`)}
    <div class="grid kpis" style="grid-template-columns:repeat(4,1fr)">${kpi('Active workflows','38','10 approval routes',{accent:true})}${kpi('Automated tasks','12,481','last 30 days',{})}${kpi('Human approvals','27','median 3.4h',{})}${kpi('Escalations','7','2 overdue',{})}</div>
    <div class="card panel"><div class="panel-head"><h3>Workflow builder canvas</h3><span class="sub">trigger → conditions → actions → evidence</span></div><div class="workflow-canvas">${['Trigger: invoice.past_due','If balance > $5k','Send email + SMS','Wait 3 business days','Escalate to collector','Create audit evidence'].map((x,i)=>`<div class="flow-node" data-act="workflowstep" data-arg="${i+1}|${x}" style="cursor:pointer"><i>${i+1}</i><b>${x}</b><span>${i===1?'customer segment + risk tier checked':'configured'}</span></div>`).join('')}</div></div>
    <div class="two-col" style="align-items:start;margin-top:16px"><div class="card panel"><div class="panel-head"><h3>Published workflows</h3></div><div class="table-wrap"><table><thead><tr><th>Name</th><th>Trigger</th><th>Route</th><th>Status</th></tr></thead><tbody>${flows.map(f=>`<tr data-act="workflowdetail" data-arg="${f[0]}|${f[1]}|${f[2]}|${f[3]}" style="cursor:pointer"><td class="nm">${f[0]}</td><td class="mono">${f[1]}</td><td>${f[2]}</td><td>${pill(f[4],f[3])}</td></tr>`).join('')}</tbody></table></div></div><div class="card panel"><div class="panel-head"><h3>Run history</h3></div><div class="table-wrap"><table><thead><tr><th>ID</th><th>Flow</th><th>Step</th><th>Account</th><th>State</th></tr></thead><tbody>${runs.map(r=>`<tr data-act="workflowrun" data-arg="${r[0]}|${r[1]}|${r[2]}|${r[3]}|${r[4]}" style="cursor:pointer"><td class="mono">${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td><td class="mut">${r[4]}</td></tr>`).join('')}</tbody></table></div></div></div>
  </div>`));
};
